name: Deploy WordPress Theme

on:
  push:
    branches:
      - "arena/019fa329-landing"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz repo
        uses: actions/checkout@v6

      - name: Wyślij motyw na InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /htdocs/wp-content/themes/autoserwis/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .dev/**
            **/node_modules/**
            **/*.md
            LICENSE
